version: '3'

volumes:
  pgdata:
    driver: local


services:
  # переписать
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/www/db_data/postgresql/lamiachan
      volumes:
        - pgdata:/var/www/db_data/postgresql/lamiachan

  django:
    restart: always
    image: registry.gitlab.com/mar4elkin/lamia_chan_web_devops/backend
    # build:
    #     context: ./backend 
    #     dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    restart: always
    image: nginx:1.17.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - vue
  
  vue:
    restart: always
    image: registry.gitlab.com/mar4elkin/lamia_chan_web_devops/frontend
    # build:
    #     context: ./frontend
    #     dockerfile: Dockerfile
    command: npm run serve  
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - django


