version: '3'

services:
  django:
    build:
        context: ./backend 
        dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
  vue:
    build:
        context: ./frontend
        dockerfile: Dockerfile
    command: npm run serve  
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    ports:
      - "8080:8080"
 
    
    


