version: '3'

services:
  vue:
    build: ./frontend/Lamia_chan
    command: npm run serve
    volumes:
        - .:/app
    ports:
        - "8080:8080"

  django:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

 
    
    


