version: '3'

volumes:
  pgdata:
    driver: local


services:
  # переписать
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
      
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
      PGDATA: /var/www/db_data/postgresql/lamiachan
    volumes:
      - pgdata:/var/www/db_data/postgresql/lamiachan

  django:
    restart: always
    image: registry.gitlab.com/mar4elkin/lamia_chan_web_devops/backend
    # build:
    #     context: ./backend 
    #     dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/srv/www/lamiachan/backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  nginx:
    restart: always
    image: nginx:1.17.4-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - react

  react:
    restart: always
    # разобраться с ошибкой node_models
    #image: registry.gitlab.com/mar4elkin/lamia_chan_web_devops/frontend
    build:
        context: ./frontend
        dockerfile: Dockerfile
    volumes:
        - ./frontend:/srv/www/lamiachan/frontend
        - ./srv/www/lamiachan/frontend/node_modules
    ports:
        - "3000:3000"
    depends_on:
      - django
    stdin_open: true
    tty: true



