version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
  django:
    restart: always
    build:
        context: ./backend 
        dockerfile: Dockerfile
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  vue:
    restart: always
    build:
        context: ./frontend
        dockerfile: Dockerfile
    command: npm run serve  
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    ports:
      - "8080:8080"

