version: '3.3'

volumes:
    lamia_chan: {}

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  frontend:
    build:
      context: ./frontend/Lamia_chan
    #image: node:lts-alpine
    #command: npm run serve
    volumes:
      - ./.env:/app/.env:ro
      - ./frontend/Lamia_chan:/app
    working_dir: /app
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
