# Generated by Django 2.2.6 on 2019-12-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ch_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_genre', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Manga_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_manga', models.IntegerField()),
                ('id_vol', models.IntegerField()),
                ('id_chapter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vol_name', models.CharField(max_length=256)),
            ],
        ),
    ]
