# Generated by Django 2.2.6 on 2019-12-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_manga_id_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='manga')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Manga_Detail',
        ),
        migrations.DeleteModel(
            name='Vols',
        ),
        migrations.RenameField(
            model_name='chapters',
            old_name='ch_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='manga',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='manga',
            name='chapters',
            field=models.ManyToManyField(to='core.Chapters'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='chapters',
            name='pages',
            field=models.ManyToManyField(to='core.Pages'),
        ),
        migrations.AddField(
            model_name='manga',
            name='sources',
            field=models.ManyToManyField(to='core.Source'),
        ),
    ]
