# Generated by Django 2.2.6 on 2019-12-12 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191212_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='manga')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chapter')),
            ],
        ),
        migrations.RemoveField(
            model_name='manga',
            name='chapters',
        ),
        migrations.DeleteModel(
            name='Chapters',
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
        migrations.AddField(
            model_name='chapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Manga'),
        ),
    ]
