# Generated by Django 3.0 on 2020-02-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_favorite_manga',
            field=models.ManyToManyField(to='core.Manga'),
        ),
    ]
