# Generated by Django 3.0 on 2020-02-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200218_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('BG', 'Новичок'), ('MD', 'Завсегдатый'), ('HG', 'Боженька'), ('MG', 'Модератор')], default='BG', max_length=2),
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
