# Generated by Django 3.0 on 2019-12-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191212_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='preview_image_url',
            field=models.CharField(default='none', max_length=256),
        ),
    ]
