# Generated by Django 3.0 on 2019-12-16 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_manga_preview_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Manga')),
            ],
        ),
    ]
