# Generated by Django 3.0 on 2020-02-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200218_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, to='core.Chapter'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('BG', 'Новичок'), ('MD', 'Завсегдатый'), ('HG', 'Боженька'), ('MG', 'Модератор'), ('JS', 'Жидо-скриптизер'), ('DJ', 'Хозяин-питона')], default='BG', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_favorite_manga',
            field=models.ManyToManyField(blank=True, null=True, to='core.Manga'),
        ),
    ]
