# Generated by Django 3.0 on 2020-02-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191225_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='preview_image_url',
            field=models.ImageField(upload_to='manga'),
        ),
    ]
