# Generated by Django 3.0.3 on 2020-02-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_report_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='object_type',
            field=models.CharField(choices=[('Манга', 'Манга'), ('Манхва', 'Манхва'), ('Маньхуа', 'Маньхуа'), ('Ранобэ', 'Ранобэ')], default='Манга', max_length=30),
        ),
        migrations.AddField(
            model_name='manga',
            name='translating_status',
            field=models.CharField(choices=[('Ожидает загрузки', 'Ожидает загрузки'), ('Заброшенно', 'Заброшенно'), ('Продолжается', 'Продолжается'), ('Переведено', 'Переведено')], default='Ожидает загрузки', max_length=30),
        ),
        migrations.AddField(
            model_name='manga',
            name='year_of_publish',
            field=models.CharField(default='empty', max_length=200),
        ),
    ]
