# Generated by Django 3.0 on 2020-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200202_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
