# Generated by Django 3.0.3 on 2020-02-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200220_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='year_of_publish',
            field=models.DateTimeField(),
        ),
    ]
