# Generated by Django 3.0.3 on 2020-03-03 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200220_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
