# Generated by Django 3.0 on 2020-02-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200203_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='status_of_manga',
        ),
    ]
