# Generated by Django 3.0.3 on 2020-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_manga_status_of_manga'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
