# Generated by Django 3.0.3 on 2020-03-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200303_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
