# Generated by Django 3.0 on 2020-02-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_manga_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
