# Generated by Django 3.0.3 on 2020-03-03 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200303_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
