# Generated by Django 3.0 on 2020-02-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chapter_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='updated',
        ),
    ]
