# Generated by Django 3.0.3 on 2020-03-03 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200303_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='upload_date',
        ),
    ]
