# Generated by Django 3.0.3 on 2020-04-08 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_manga_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='DateUp',
        ),
        migrations.AddField(
            model_name='manga',
            name='nswf',
            field=models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, to='core.Page'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('Новичок', 'Новичок'), ('Завсегдатый', 'Завсегдатый'), ('Боженька', 'Боженька'), ('Модератор', 'Модератор'), ('Жидо-скриптизер', 'Жидо-скриптизер'), ('Хозяин-питона', 'Хозяин-питона'), ('Джабист', 'Джабист'), ('Веб хуежник', 'Веб хуежник')], default='Новичок', max_length=30),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Page'),
        ),
    ]
