# Generated by Django 3.0 on 2020-02-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_mangauser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangauser',
            old_name='user_abot',
            new_name='user_moto',
        ),
    ]
