# Generated by Django 3.0.3 on 2020-04-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200408_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default='', null=True, to='core.Page'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_favorite_manga',
            field=models.ManyToManyField(blank=True, default='', null=True, to='core.Manga'),
        ),
    ]
