# Generated by Django 3.0.3 on 2020-04-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200411_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
