# Generated by Django 3.0.3 on 2020-04-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_manga_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='gradient_color1',
            field=models.CharField(default='empty', max_length=50),
        ),
        migrations.AddField(
            model_name='manga',
            name='gradient_color2',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
