# Generated by Django 3.0.3 on 2020-05-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200423_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_favorite_manga',
            field=models.ManyToManyField(blank=True, null=True, to='core.Manga'),
        ),
    ]
