# Generated by Django 3.0.3 on 2020-05-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200518_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, null=True, to='core.Page'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_favorite_manga',
            field=models.ManyToManyField(blank=True, null=True, to='core.Manga'),
        ),
    ]
