# Generated by Django 3.0.3 on 2020-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200519_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='url_name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
