# Generated by Django 3.0.3 on 2020-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_manga_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='url_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
