# Generated by Django 3.0.3 on 2020-09-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200519_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='sources',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
