# Generated by Django 3.0.3 on 2020-10-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200930_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='translater',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='loved_tags',
            field=models.ManyToManyField(blank=True, default=None, to='core.Tag'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_big_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='upicks'),
        ),
    ]
