name: Publish on Docker Hub and Deploy

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout Project"
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: "Docker Build"
      run: docker-compose --log-level INFO up -d --build

    - name: "Docker Logs"
      run: docker-compose logs

  build_and_pub:
    # Если тесты были пройдены успешно
    needs: [build]
    runs-on: [ubuntu-latest]
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST http://queryberry.ru/updater
